# Default values for ard-campaign.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

worker:
  image:
    repository: "satapps/ard-workflow-s2"
    tag: "1.2.1"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  parallelism: 3
  resources: {}
  env: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

jupyter:
  enabled: true
  image:
    repository: "satapps/ard-workflow-s2-jupyter"
    tag: "1.2.1"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  service:
    type: LoadBalancer
    port: 80
  replicaCount: 1
  resources: {}
  env: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

redisServiceHost: "redis-master"

gcp:
  privateKey: "-----BEGIN PRIVATE KEY-----\\n...\\n-----END PRIVATE KEY-----"
  clientEmail: "invalid@nvalid.iam.gserviceaccount.com"

aws:
  accessKeyId: "AKIAIOSFODNN7INVALID"
  secretAccessKey: "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"
