{{ if .Values.jupyter.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ard-campaign.fullname" . }}-jupyter
  labels:
{{ include "ard-campaign.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.jupyter.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ard-campaign.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: jupyter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ard-campaign.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: jupyter
    spec:
    {{- with .Values.jupyter.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}"
          imagePullPolicy: {{ .Values.jupyter.image.pullPolicy }}
          resources:
            {{- toYaml .Values.jupyter.resources | nindent 12 }}
          env:
            - name: ASF_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "ard-campaign.fullname" . }}
                  key: asf_username
            - name: ASF_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ard-campaign.fullname" . }}
                  key: asf_password
            - name: COPERNICUS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "ard-campaign.fullname" . }}
                  key: copernicus_username
            - name: COPERNICUS_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ard-campaign.fullname" . }}
                  key: copernicus_password
            - name: GCP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ard-campaign.fullname" . }}
                  key: gcp_private_key
            - name: GCP_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ard-campaign.fullname" . }}
                  key: gcp_client_email
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "ard-campaign.fullname" . }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ard-campaign.fullname" . }}
                  key: aws_secret_access_key
            {{- if .Values.jupyter.env }}
            {{- $extraEnvType := typeOf .Values.jupyter.env }}
            {{- /* If we have a list, embed that here directly. This allows for complex configuration from configmap, downward API, etc. */}}
            {{- if eq $extraEnvType "[]interface {}" }}
            {{- .Values.jupyter.env | toYaml | trimSuffix "\n" | nindent 12 }}
            {{- else if eq $extraEnvType "map[string]interface {}" }}
            {{- /* If we have a map, treat those as key-value pairs. */}}
            {{- range $key, $value := .Values.jupyter.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
    {{- with .Values.jupyter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jupyter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jupyter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

{{- end }}
