apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ard-campaign.fullname" . }}
  labels:
    app: {{ include "ard-campaign.name" . }}
    chart: {{ include "ard-campaign.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.aws.accessKeyId | b64enc }}
  aws_secret_access_key: {{ .Values.aws.secretAccessKey | b64enc }}
  gcp_private_key: {{ .Values.gcp.privateKey | b64enc }}
  gcp_client_email: {{ .Values.gcp.clientEmail | b64enc }}
