apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ard-cronjob.fullname" . }}
  labels:
    app: {{ include "ard-cronjob.name" . }}
    chart: {{ include "ard-cronjob.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  asf_username: {{ .Values.asf.username | b64enc }}
  asf_password: {{ .Values.asf.password | b64enc }}
  copernicus_username: {{ .Values.copernicus.username | b64enc }}
  copernicus_password: {{ .Values.copernicus.password | b64enc }}
  aws_access_key_id: {{ .Values.aws.accessKeyId | b64enc }}
  aws_secret_access_key: {{ .Values.aws.secretAccessKey | b64enc }}
  gcp_private_key: {{ .Values.gcp.privateKey | b64enc }}
  gcp_client_email: {{ .Values.gcp.clientEmail | b64enc }}
