apiVersion: v1
kind: ConfigMap
metadata:
  name: users-conf
  labels:
{{ include "cube-query.labels" . | indent 4 }}
data:
  users.cfg: |
    # User, password hash (bcrypt), allowed addresses
    basic,$2b$12$LJxr6ilLLg.wSfiFGLp1w.s1A6H23z/6oV6qlcA/4..HoZNjMi/Uy,127.0.0.1;10.*
