{{- if .Values.server.usersConf }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: users-conf
  labels:
{{ include "cube-query.labels" . | indent 4 }}
data:
  users.cfg: |
    {{- .Values.server.usersConf | nindent 4 }}

{{- end }}
