apiVersion: batch/v1
kind: Deployment
metadata:
  name: {{ include "cube-query.fullname" . }}-worker
  labels:
{{ include "cube-query.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cube-query.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cube-query.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: worker
    spec:
      restartPolicy: OnFailure
    {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/datacube.conf
              name: datacube-conf
              subPath: datacube.conf
          env:
            - name: REDIS_URL
              value: "redis://{{ .Values.redisServiceHost }}:6379/"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "cube-query.fullname" . }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cube-query.fullname" . }}
                  key: aws_secret_access_key
            {{- if .Values.worker.env }}
            {{- $extraEnvType := typeOf .Values.worker.env }}
            {{- /* If we have a list, embed that here directly. This allows for complex configuration from configmap, downward API, etc. */}}
            {{- if eq $extraEnvType "[]interface {}" }}
            {{- .Values.worker.env | toYaml | trimSuffix "\n" | nindent 12 }}
            {{- else if eq $extraEnvType "map[string]interface {}" }}
            {{- /* If we have a map, treat those as key-value pairs. */}}
            {{- range $key, $value := .Values.worker.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
      volumes:
        - configMap:
            defaultMode: 420
            name: datacube-conf
          name: datacube-conf
    {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
