apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ard-workflow-s2.fullname" . }}
  labels:
{{ include "ard-workflow-s2.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ard-workflow-s2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ard-workflow-s2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: worker
    spec:
    {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          env:
            {{- toYaml .Values.worker.env | nindent 12 }}
    {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
