apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cube-query.fullname" . }}
  labels:
    app: {{ include "cube-query.name" . }}
    chart: {{ include "cube-query.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.aws.accessKeyId | b64enc }}
  aws_secret_access_key: {{ .Values.aws.secretAccessKey | b64enc }}
