{{ if .Values.jupyter.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "ard-workflow.fullname" . }}-jupyter
  labels:
{{ include "ard-workflow.labels" . | indent 4 }}
spec:
  type: {{ .Values.jupyter.service.type }}
  ports:
    - port: {{ .Values.jupyter.service.port }}
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ard-workflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- end }}
